baseurl = "https://hopeful-montalcini-39c80e.netlify.com/"
title = "useR template"
theme = ["hugo-user-theme","hugo-universal-theme"]
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[menu]

# Main menu
# Comment out sections to prevent them appearing on the nav bar
[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Program"
    url  = "/program/"
    weight = 2

[[menu.main]]
    name = "Participation"
    url  = "/participation/"
    weight = 3

[[menu.main]]
    name = "Venue"
    url  = "/venue/"
    weight = 4

[[menu.main]]
   name = "News"
   url  = "/news/"
   weight = 5
   
[[menu.main]]
   name = "FAQ"
   identifier = "faq"
   url  = "/faq/"
   weight = 6

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 7

[[menu.main]]
    name = "Code of Conduct"
    url  = "/codeofconduct/"
    weight = 8

[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 9

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Twitter"
    url = "https://twitter.com/user2018_conf"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "/contact"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/news/"
    author = "DevCows"
    defaultKeywords = ["devows", "hugo", "go"]
    defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "your@email.com"

    about_us = """<p><strong>
    @twitter_handle // #conference_tag</strong>
    <br>See something wrong? Submit a PR on GitHub
    </p>
    """
    copyright = "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/userlogo-small.png"
    logo_small = "img/userlogo-small.png"
    address = """<p><strong>Universal Ltd.</strong>
        <br>13/25 New Avenue
        <br>Newtown upon River
        <br>45Y 73J
        <br>England
        <br>
        <strong>Great Britain</strong>
      </p>
      """
    latitude = "-12.043333"
    longitude = "-77.028333"

[Permalinks]
    blog = "/news/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true
    contact_map = false

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.twitter]
    enable = true
    bg = false
    pattern = false
    photo1 = true
    photo2 = false
    title = "Twitter"
    feed_url = "https://twitter.com/user2018_conf"

[params.sponsors]
    enable = true
    bg = false
    pattern = true
    photo1 = false
    photo2 = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Sponsors"
    tier1 = "Gold"
    tier2 = "Silver"
    tier2scale ="80%"
    tier3 = "Bronze"
    tier3scale ="30%"

[params.recent_posts]
    enable = true
    title = "News"
    subtitle = ""

[params.participation]
    tickets_enable = true
    tickets_link = "http://www.tickets.com"
    tickets_text = "Get your ticket"
    cfp_enable = true
    cfp_link = "http://www.callforpapers.com"
    cfp_text = "Submit your paper"

[params.organising]
    enable = true
    bg = true
    pattern= false
    photo1 = false
    photo2 = false
    # Possibility to center items
    center = true
    title = "Team"
    subtitle = "Organising Commitee"
    description = "Local team organising the event"

    # All organising member's pictures are stored under 'static/img/organising'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.organising.members]]
      img = "faceholder.png"
      name = "Organiser Name 1"
      position = "Organiser Position 1"
      reportsTo = "Some Person"
      livesIn = "[Munich, Germany](#some-maps-url)"
      scope = [
        "Role 1 for [thing 1](#)",
        "Role 2 for [thing 2](#)",
        "Role 3 for [thing 3](#)"
      ]
      # For bio markdown and even multiline strings are available.
      bio = """I do things,
      and stuff"""
      social = [
        ["fa-twitter", "#"],
        ["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.organising.members]]
      img = "faceholder.png"
      name = "Organiser Name 2"
      position = "Organiser Position 2"
      social = [
        ["fa-twitter", "#"],
        ["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.organising.members]]
      img = "faceholder.png"
      name = "Organiser Name 3"
      position = "Organiser Position 3"
      social = [
        ["fa-twitter", "#"],
        ["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]
    
    [[params.organising.members]]
      img = "faceholder.png"
      name = "Organiser Name 4"
      position = "Organiser Position 4"
      social = [
        ["fa-twitter", "#"],
        ["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.organising.members]]
      img = "faceholder.png"
      name = "Organiser Name 5"
      position = "Organiser Position 5"
      social = [
        ["fa-twitter", "#"],
        ["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.organising.members]]
      img = "faceholder.png"
      name = "Organiser Name 6"
      position = "Organiser Position 6"
      social = [
        ["fa-twitter", "#"],
        ["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

[params.programming]
    enable = true
    bg = true
    pattern = false
    photo1 = false
    photo2 = false
    # Possibility to center items
    center = true
    # title = ""
    subtitle = "Programming Comitee"
    description = "Program the thing"

    # All programming member's pictures are stored under 'static/img/programming'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.programming.members]]
      img = "faceholder.png"
      name = "Programmer Name 1"
      position = "Programmer Position 1"
      reportsTo = "Some Person"
      livesIn = "[Munich, Germany](#some-maps-url)"
      scope = [
        "Role 1 for [thing 1](#)",
        "Role 2 for [thing 2](#)",
        "Role 3 for [thing 3](#)"
      ]
      # For bio markdown and even multiline strings are available.
      bio = """I do things,
      and stuff"""
      social = [
        ["fa-twitter", "#"],
        ["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.programming.members]]
      img = "faceholder.png"
      name = "Programmer Name 2"
      position = "Programmer Position 2"
      social = [
        ["fa-twitter", "#"],
        ["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.programming.members]]
      img = "faceholder.png"
      name = "Programmer Name 3"
      position = "Programmer Position 3"
      social = [
        ["fa-twitter", "#"],
        ["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.programming.members]]
      img = "faceholder.png"
      name = "Programmer Name 4"
      position = "Programmer Position 4"
      social = [
        ["fa-twitter", "#"],
        ["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.programming.members]]
      img = "faceholder.png"
      name = "Programmer Name 5"
      position = "Programmer Position 5"
      social = [
        ["fa-twitter", "#"],
        ["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.programming.members]]
      img = "faceholder.png"
      name = "Programmer Name 6"
      position = "Programmer Position 6"
      social = [
        ["fa-twitter", "#"],
        ["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

[params.foundation]
    enable = true
    bg = true
    pattern = false
    photo1 = false
    photo2 = false
    # Possibility to center items
    center = true
    # title = "Team"
    subtitle = "R Foundation"
    description = "Foundation members"

    # All foundation member's pictures are stored under 'static/img/foundation'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.foundation.members]]
      img = "faceholder.png"
      name = "Foundation Name 1"
      position = "Foundation Position 1"
      reportsTo = "Some Person"
      livesIn = "[Munich, Germany](#some-maps-url)"
      scope = [
        "Role 1 for [thing 1](#)",
        "Role 2 for [thing 2](#)",
        "Role 3 for [thing 3](#)"
      ]
      # For bio markdown and even multiline strings are available.
      bio = """I do things,
      and stuff"""
      social = [
        ["fa-twitter", "#"],
        ["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.foundation.members]]
      img = "faceholder.png"
      name = "Foundation Name 2"
      position = "Foundation Position 2"
      social = [
        ["fa-twitter", "#"],
        ["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.foundation.members]]
      img = "faceholder.png"
      name = "Foundation Name 3"
      position = "Foundation Position 3"
      social = [
        ["fa-twitter", "#"],
        ["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.foundation.members]]
      img = "faceholder.png"
      name = "Foundation Name 4"
      position = "Foundation Position 4"
      social = [
        ["fa-twitter", "#"],
        ["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.foundation.members]]
      img = "faceholder.png"
      name = "Foundation Name 5"
      position = "Foundation Position 5"
      social = [
        ["fa-twitter", "#"],
        ["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

    [[params.foundation.members]]
      img = "faceholder.png"
      name = "Foundation Name 6"
      position = "Foundation Position 6"
      social = [
        ["fa-twitter", "#"],
        ["fa-github", "#"],
        ["fa-linkedin", "#"]
      ]

[params.dates]
    enable = true
    bg = true
    pattern = false
    photo1 = false
    photo2 = false
    title = "Important Dates"
    # subtitle="Don't forget these!"

[params.about]
    enable = true
    bg = true
    pattern = false
    photo1 = false
    photo2 = false
    title = "Conference Overview"
    subtitle = "About the event"
    text = "The conference is going to be super-great, awesome and rocking!! It _even_ **supports** [markdown](https://gohugo.io/content-management/formats/#learn-markdown)!!!"